site_name: My Data Analytics Docs
site_url: https://fdmsantos.github.io/my-data-analytics-docs/
site_description: My documentation related with Data Engineering/Data Analytics
site_author: Fábio Santos
theme:
  name: material
  navigation_depth: 4

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - HDFS: hdfs.md
  - Hive: hive.md
  - Flink: flink.md